include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cloudxns
PKG_VERSION:=1.1.1
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for CloudXNS
LUCI_DEPENDS:=+curl +libcurl
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

#$(eval $(call BuildPackage,luci-app-cloudxns))