#!/bin/sh /etc/rc.common
START=80

restart()
{                                                                                                       
	killall cloudxns.sh
	/usr/share/cloudxns.sh
}

start()
{
	/usr/share/cloudxns.sh
}

stop()
{
	killall cloudxns.sh
}
